### ISSUE TITLE
Auto jumping to web browser instead of showing in app's webview

### ISSUE THREAD

**Issue by voidregreso** [sakusaku3939/DeepLAndroid#77] opened 2022-03-29 16:13 UTC
As mentioned above, every time I open the app, the launch page automatically displays "Jump to external browser" after a few seconds instead of inside the app's internal webview.
![image](https://user-images.githubusercontent.com/8023790/160657354-bc6f0a34-d81f-40da-9e25-8a155e3b41a5.png)

And after checking the logs, I find a persistent error: "Uncaught ReferenceError : $ is not defined". 
![image](https://user-images.githubusercontent.com/8023790/160657388-77d11e39-afd8-405c-9023-6b42bb9bf4a1.png)

I hope this can be fixed.

**Comment by sakusaku3939** [comment] 2022-03-30 06:18
Thanks for reporting it!
I was able to reproduce the problem on some devices and investigated in detail.


### Regarding the "jump to external browser" issue.
Fixing `shouldOverrideUrlLoading` solved the problem. However, as described below, the code of the DeepL server has changed significantly, so the display is the same as when opened in a browser.

The fix for this problem worked on the old version of the DeepL server, so we have released it first as v7.3!
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v7.3

### Regarding the "$ is not defined" error.
It is likely that jQuery is not used in newer versions.
Therefore, we are considering whether to rewrite all previous code in vanilla JS or dynamically load jQuery.

### Regarding the issue of all class and id names being changed.
It turns out that when the DeepL server gets a new version, all the internal structure, class names, and id names are changed.

I usually use the developer mode of the browser when identifying the elements I want to hide. However, currently my browser does not yet reflect the new version, so it will take some time to fix the problem.
<br>

Finally, I am happy to report that an official Android version of the app is now available from DeepL!
https://play.google.com/store/apps/details?id=com.deepl.mobiletranslator&referrer=utm_source%3Ddeepl%26utm_campaign%3DpageID400-m-first-cta%26anid%3Dadmob

(And since the only problem that was inconvenient for me has been solved, I am a little less motivated to develop:cry:)

**Comment by sakusaku3939** [comment] 2022-04-10 17:22
Thanks for your waiting! Partial, but fixed to hide unwanted elements and copy button works.
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v7.4

The display of the language switch button and the adjustment of the visibility in dark mode will be fixed in the future.

Please report if it does not work properly.

**Closed** 2022-04-18 04:16 UTC
