### ISSUE TITLE
Text containing "#" is not translated correctly when using the floating text selection action

### ISSUE THREAD

**Issue by sckemu** [sakusaku3939/DeepLAndroid#5] opened 2021-05-22 10:12 UTC
Thanks for making this app! It is very useful! 
However, if you use the floating text selection action to select text with a "#" inside, the text after the "#" will not be translated.

**Comment by fm-sys** [comment] 2021-05-22 12:06
Related to / duplicate of #6 - it's a more generic issue, all special URL characters need to be escaped

**Closed** 2021-05-27 09:04 UTC
